### ISSUE TITLE
Cannot repoduce the results with the pretrained model

### ISSUE THREAD

**Issue by houxianxu** [kimy-de/HiddenFluidMechanics#1]
First, thanks a lot for sharing the Pytorch-based implementation of HFM.

I've tried to use the pretrained model to reproduce the results with `python evaluation.py --modelpath './hfm_0.pth'`. However, I cannot get the results as shown in the _results_ folder. Am I missing something? 

I've attached the obtained _error_graph_ and _last_time_prediction_.

Thanks

![error_graph](https://user-images.githubusercontent.com/3723839/162612840-4e6f27a5-9baa-4a0f-b283-9b0b428bce2f.png)
 
![last_time_prediction](https://user-images.githubusercontent.com/3723839/162612890-7cb72b55-392a-4f41-9046-88ed7040c966.png)

**Comment by kimy-de** [comment]
Thank you for your interest in my code. It should work. Can you try the new one that I uploaded today? If it also doesn't work, you can train the model on your own.

**Comment by houxianxu** [comment]
Thanks for your reply, I will try the new one.
